import { LEVELS, LEVEL_INFO, PRESETS, resolvePolicy } from './policy.js';

// Everything a maintainer reads — AI_POLICY.md, the PR template section, the
// workflow — is generated from the one config file, so the documents and the
// check can never disagree. No Node APIs here: this also runs in a browser.

export const DOC_NOTICE = '<!-- Generated by declared from .github/ai-policy.yml. Edit that file, then run `npx declared render`. -->';
export const TEMPLATE_START = '<!-- declared:start -->';
export const TEMPLATE_END = '<!-- declared:end -->';
export const DEFAULT_USES = 'OWNER/declared@v1';
/** The npm package name; "declared" itself is taken on npm by an unrelated package. */
export const NPM_PACKAGE = 'declared-ai';

/** Stable FNV-1a hash of the effective policy (ignores comments and formatting). */
export function policyHash(policy) {
  const canonical = JSON.stringify(policy, (_, v) =>
    v && typeof v === 'object' && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => a.localeCompare(b)))
      : v);
  let h = 0x811c9dc5;
  for (let i = 0; i < canonical.length; i++) {
    h ^= canonical.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

export function readDocHash(markdown) {
  return /<!-- declared:hash=([0-9a-f]{8}) -->/.exec(markdown ?? '')?.[1] ?? null;
}

function yamlValue(v) {
  if (Array.isArray(v)) return `[${v.map(yamlValue).join(', ')}]`;
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  const s = String(v);
  const plain = /^[A-Za-z_][A-Za-z0-9._/-]*$/.test(s) && !/^(true|false|null|yes|no|on|off|~)$/i.test(s);
  return plain ? s : JSON.stringify(s);
}

/** A fully commented config file for a preset, with optional overrides (e.g. { project, require: {...} }). */
export function renderPolicyYaml(presetName = 'disclose', overrides = {}) {
  const p = resolvePolicy({ ...overrides, preset: presetName });
  const v = yamlValue;
  const lines = [
    '# AI contribution policy, read by the `declared` GitHub Action and CLI.',
    `# Started from the "${presetName}" preset: ${PRESETS[presetName].summary}`,
    '# AI_POLICY.md and the PR template section are generated from this file:',
    '#   npx declared render',
    'version: 1',
    `preset: ${v(presetName)}   # open | disclose | strict | human-only (values below override it)`,
    `project: ${v(p.project)}`,
    `policy-url: ${v(p['policy-url'])}`,
    '',
    '# Disclosure levels this project accepts: none, ai-assisted, ai-generated, autonomous',
    `allowed-levels: ${v(p['allowed-levels'])}`,
    '',
    'require:',
    `  disclosure: ${v(p.require.disclosure)}        # the PR description declares a level`,
    `  tool: ${v(p.require.tool)}              # AI-assisted PRs name the tool: "Assisted-by: Tool:model"`,
    `  scope: ${v(p.require.scope)}             # ...and say what the AI did: "AI-Scope: ..."`,
    `  attestation: ${v(p.require.attestation)}       # ...and confirm a human reviewed and understands it`,
    `  commit-trailers: ${v(p.require['commit-trailers'])}  # ...and mark each commit with an Assisted-by trailer`,
    '',
    `consistency: ${v(p.consistency)}   # compare the declaration with AI trailers found in commits`,
    '',
    'media:',
    `  forbid-ai-generated: ${v(p.media['forbid-ai-generated'])}   # PRs adding images/audio/video confirm they are not AI-made`,
    '',
    'first-time-contributors:',
    `  max-changed-lines: ${v(p['first-time-contributors']['max-changed-lines'])}   # size cap for AI-assisted first PRs (0 = none)`,
    '',
    'exempt:',
    `  authors: ${v(p.exempt.authors)}`,
    `  associations: ${v(p.exempt.associations)}   # e.g. OWNER, MEMBER, COLLABORATOR`,
    `  labels: ${v(p.exempt.labels)}`,
    '',
    `drafts: ${v(p.drafts)}         # warn | enforce | skip`,
    `enforcement: ${v(p.enforcement)}    # fail = failing check; warn = comment and labels only`,
    `comment: ${v(p.comment)}`,
    '',
    'labels:',
    ...LEVELS.map((l) => `  ${l}: ${v(p.labels[l])}`),
    `  missing: ${v(p.labels.missing)}`,
    '',
  ];
  return lines.join('\n');
}

function exampleDisclosure(policy) {
  const allowed = policy['allowed-levels'];
  if (!allowed.some((l) => l !== 'none')) return 'AI-Disclosure: none';
  const lines = [
    `AI-Disclosure: ${allowed.includes('ai-assisted') ? 'ai-assisted' : allowed.find((l) => l !== 'none')}`,
    'Assisted-by: Claude Code:claude-opus-5',
  ];
  if (policy.require.scope) lines.push('AI-Scope: generated the test fixtures; I wrote and reviewed the parser changes');
  if (policy.require.attestation) lines.push('', '- [x] I have reviewed every change in this PR and can explain it without AI help.');
  return lines.join('\n');
}

function stance(policy) {
  const allowed = policy['allowed-levels'];
  if (allowed.length === 1 && allowed[0] === 'none') {
    return 'This project does not accept contributions created with generative AI tools. Every pull request confirms that no AI tools were used.';
  }
  const parts = ['AI tools are welcome here, as long as a person stays responsible for the result.'];
  parts.push(policy.enforcement === 'warn'
    ? 'Please say whether and how you used them; it helps reviewers focus.'
    : 'Every pull request must say whether and how they were used.');
  return parts.join(' ');
}

/** AI_POLICY.md, in plain language, derived from the policy. */
export function renderPolicyDoc(policy) {
  const p = policy;
  const allowed = p['allowed-levels'];
  const human = allowed.length === 1 && allowed[0] === 'none';
  const title = p.project ? `# AI contribution policy for ${p.project}` : '# AI contribution policy';
  const out = [DOC_NOTICE, `<!-- declared:hash=${policyHash(p)} -->`, '', title, '', stance(p), ''];

  out.push('## What to write in your pull request', '');
  out.push('Add these lines to the pull request description (the template already has them):', '');
  out.push('```', exampleDisclosure(p), '```', '');

  out.push('## Disclosure levels', '', '| Level | Meaning | Accepted |', '| --- | --- | --- |');
  for (const level of LEVELS) {
    out.push(`| \`${level}\` | ${LEVEL_INFO[level]} | ${allowed.includes(level) ? 'yes' : 'no'} |`);
  }
  out.push('');

  const rules = [];
  if (p.require.disclosure) rules.push('Every pull request declares exactly one level with `AI-Disclosure:`.');
  if (!human) {
    if (p.require.tool) rules.push('If AI helped, name the tool and model with `Assisted-by: Tool:model` (the Linux kernel format). List several tools with commas.');
    if (p.require.scope) rules.push('If AI helped, describe what it did with `AI-Scope:`.');
    if (p.require.attestation) rules.push('If AI helped, confirm you reviewed every change and can explain it without AI help. If you cannot, please do not submit it.');
    if (p.require['commit-trailers']) rules.push('If AI helped, each commit carries an `Assisted-by: Tool:model` trailer.');
    const cap = p['first-time-contributors']['max-changed-lines'];
    if (cap > 0) rules.push(`First-time contributors keep AI-assisted pull requests under ${cap} changed lines. For anything bigger, open an issue first.`);
  }
  if (p.media['forbid-ai-generated']) rules.push('No AI-generated images, audio or video. Pull requests that add media confirm it was made without AI.');
  if (p.consistency) rules.push('The disclosure should match your commits. Many AI tools add `Co-authored-by` or `Assisted-by` trailers on their own; if yours did, disclose it.');
  if (rules.length) out.push('## Rules', '', ...rules.map((r) => `- ${r}`), '');

  if (!human && !p.require['commit-trailers']) {
    out.push('## Commits', '', 'Marking commits is optional but appreciated:', '', '```', 'git commit --trailer "Assisted-by: Claude Code:claude-opus-5"', '```', '');
  }

  out.push(
    '## How this is checked',
    '',
    'An automated check reads the pull request description, commit messages and changed file names.',
    'It does **not** try to detect AI-written code; it relies on honest disclosure.',
    p.enforcement === 'warn'
      ? 'Problems are reported in a comment and never block merging.'
      : 'If something is missing, a comment explains how to fix it and the check fails until the description is updated.',
    '',
  );

  const exempt = [];
  if (p.exempt.authors.length) exempt.push(`bots and accounts: ${p.exempt.authors.map((a) => `\`${a}\``).join(', ')}`);
  if (p.exempt.associations.length) exempt.push(`repository roles: ${p.exempt.associations.map((a) => a.toLowerCase()).join(', ')}`);
  if (p.exempt.labels.length) exempt.push(`pull requests labelled ${p.exempt.labels.map((l) => `\`${l}\``).join(', ')}`);
  if (exempt.length) out.push('These are exempt from the check:', '', ...exempt.map((e) => `- ${e}`), '');

  if (p.notes) out.push('## Notes from the maintainers', '', p.notes.trim(), '');
  return out.join('\n');
}

/** The disclosure block inserted into the PR template. */
export function renderPrSection(policy) {
  const allowed = policy['allowed-levels'];
  const url = policy['policy-url'];
  const lines = [TEMPLATE_START, '## AI disclosure', ''];
  lines.push(`<!-- Required. See ${url}. Choose one: ${allowed.join(' | ')} -->`);
  lines.push('AI-Disclosure: ');
  if (allowed.some((l) => l !== 'none')) {
    lines.push('<!-- If AI helped: tool and model, e.g. Claude Code:claude-opus-5 -->');
    lines.push('Assisted-by: ');
    if (policy.require.scope) lines.push('<!-- If AI helped: what did it do, and what did you do? -->', 'AI-Scope: ');
    if (policy.require.attestation) lines.push('', '- [ ] I have reviewed every change in this PR and can explain it without AI help.');
  }
  if (policy.media['forbid-ai-generated']) lines.push('- [ ] None of the images, audio or video in this PR were AI-generated.');
  lines.push(TEMPLATE_END);
  return lines.join('\n');
}

/** Insert or replace the disclosure block in an existing PR template. */
export function mergePrTemplate(existing, section) {
  const text = existing ?? '';
  const start = text.indexOf(TEMPLATE_START);
  const end = text.indexOf(TEMPLATE_END);
  if (start !== -1 && end > start) {
    return text.slice(0, start) + section + text.slice(end + TEMPLATE_END.length);
  }
  if (!text.trim()) return `${section}\n`;
  return `${text.replace(/\s*$/, '')}\n\n${section}\n`;
}

export function renderWorkflow({ uses = null } = {}) {
  // Without --uses the workflow runs the npm package directly, so it works the
  // moment the package is published and needs no Marketplace action listing.
  const step = uses
    ? `      - uses: ${uses}`
    : `      - run: npx --yes ${NPM_PACKAGE}@latest run-action
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}`;
  return `# Checks pull requests against .github/ai-policy.yml.
#
# pull_request_target lets the check comment on pull requests from forks.
# That is safe here because this job never checks out or runs code from the
# pull request: the action reads the description, commit messages and file
# names through the API, and reads the policy from the base branch.
name: AI policy

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize, ready_for_review, converted_to_draft, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ai-policy-\${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ai-policy:
    runs-on: ubuntu-latest
    steps:
${step}
`;
}
